# $ docker context create garden-playground --docker "host=ssh://wilfred@playground.garden-lang.org"
# $ docker context use garden-playground
# $ docker compose up -d

services:
  garden-playground:
    image: wilfred/garden-playground:latest
    ports:
      - "0.0.0.0:3000:3000"
    restart: unless-stopped
    container_name: garden-playground
